CREATE DATABASE r1bb1t;

CREATE TABLE Users (
    UserID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50),
    Handle VARCHAR(50) UNIQUE,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Description VARCHAR(255),
	Birthday DATE,
    ImageURL VARCHAR(255),
	BackgroundImageURL VARCHAR(255),
	Created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Posts (
    PostID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	UserID INT NOT NULL,
	Content VARCHAR(255),
	Created DATETIME DEFAULT CURRENT_TIMESTAMP,
	Reposts INT DEFAULT 0,
	ParentPostID INT DEFAULT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Likes (
	UserID INT NOT NULL,
    PostID INT NOT NULL,
	Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (PostID) REFERENCES Posts(PostID),
	PRIMARY KEY(UserID, PostID),
	INDEX(UserID, PostID)
);

CREATE TABLE Images (
    ImageID INT PRIMARY KEY AUTO_INCREMENT,
	UserID INT,
    PostID INT,
    ImageURL VARCHAR(255),
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (PostID) REFERENCES Posts(PostID)
);

CREATE TABLE Followers (
    FollowerID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	FollowingID INT NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FollowerID) REFERENCES Users(UserID),
    FOREIGN KEY (FollowingID) REFERENCES Users(UserID)
);